default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci if ENV['CI']
    
    api_key = app_store_connect_api_key(
      key_id: ENV['APPLE_KEY_ID'],
      issuer_id: ENV['APPLE_ISSUER_ID'],
      key_content: ENV['APPLE_PRIVATE_KEY'],
      is_key_content_base64: true
    )
    
    match(
      type: 'appstore',
      app_identifier: 'com.johnathongordon.doghealthapp',
      team_id: 'FM5C46MW5P',
      readonly: false,
      api_key: api_key
    )
    
    build_app(
      scheme: 'DogHealthApp',
      export_method: 'app-store',
      export_options: {
        teamID: 'FM5C46MW5P',
        method: 'app-store',
        uploadBitcode: false,
        uploadSymbols: true,
        compileBitcode: false
      }
    )
    
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      api_key: api_key
    )
  end
  
  desc "Setup certificates and provisioning profiles"
  lane :certificates do
    setup_ci if ENV['CI']
    
    api_key = app_store_connect_api_key(
      key_id: ENV['APPLE_KEY_ID'],
      issuer_id: ENV['APPLE_ISSUER_ID'],
      key_content: ENV['APPLE_PRIVATE_KEY'],
      is_key_content_base64: true
    )
    
    match(
      type: 'appstore',
      app_identifier: 'com.johnathongordon.doghealthapp',
      team_id: 'FM5C46MW5P',
      readonly: false,
      api_key: api_key
    )
  end
end
