name: iOS Build and TestFlight

on:
  push:
    branches: [ main, 'devin/*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Show Xcode version
      run: xcodebuild -version
      
    - name: Build iOS app for simulator
      run: |
        cd ios-app
        xcodebuild -project DogHealthApp.xcodeproj \
          -scheme DogHealthApp \
          -configuration Debug \
          -destination 'platform=iOS Simulator,name=iPhone 15' \
          build
