name: iOS Build & TestFlight

on:
  workflow_dispatch:
  push:
    branches: [ main, 'devin/*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14
    env:
      APPLE_KEY_ID: ${{ secrets.APPLE_KEY_ID }}
      APPLE_ISSUER_ID: ${{ secrets.APPLE_ISSUER_ID }}
      APPLE_PRIVATE_KEY_B64: ${{ secrets.APPLE_PRIVATE_KEY_B64 }}
      P12_BASE64: ${{ secrets.P12_BASE64 }}
      P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
      MOBILEPROVISION_BASE64: ${{ secrets.MOBILEPROVISION_BASE64 }}
      FASTLANE_DISABLE_COLORS: "1"
      LANG: en_US.UTF-8
      TZ: UTC
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with: 
        xcode-version: latest-stable

    - name: Import Code Signing Certificates
      if: ${{ ((github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/devin/'))) || (github.event_name == 'pull_request' && startsWith(github.head_ref, 'devin/'))) && env.P12_BASE64 != '' }}
      uses: apple-actions/import-codesign-certs@v2
      with:
        p12-file-base64: ${{ secrets.P12_BASE64 }}
        p12-password: ${{ secrets.P12_PASSWORD }}

    - name: Install Provisioning Profile
      if: ${{ ((github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/devin/'))) || (github.event_name == 'pull_request' && startsWith(github.head_ref, 'devin/'))) && env.MOBILEPROVISION_BASE64 != '' }}
      run: |
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        echo "$MOBILEPROVISION_BASE64" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/DogHealthApp.mobileprovision

    - name: Build iOS app for simulator (test build)
      run: |
        cd ios-app
        xcodebuild -project DogHealthApp.xcodeproj \
          -scheme DogHealthApp \
          -configuration Debug \
          -destination 'platform=iOS Simulator,name=iPhone SE (3rd generation)' \
          build

    - name: Create App Store Connect API key
      if: ${{ ((github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/devin/'))) || (github.event_name == 'pull_request' && startsWith(github.head_ref, 'devin/'))) && env.APPLE_ISSUER_ID != '' }}
      run: |
        cd ios-app
        mkdir -p .keys
        echo "$APPLE_PRIVATE_KEY_B64" | base64 --decode > .keys/AuthKey_${APPLE_KEY_ID}.p8

    - name: Archive iOS app
      if: ${{ ((github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/devin/'))) || (github.event_name == 'pull_request' && startsWith(github.head_ref, 'devin/'))) && env.P12_BASE64 != '' }}
      run: |
        cd ios-app
        xcodebuild -project DogHealthApp.xcodeproj \
          -scheme DogHealthApp \
          -configuration Release \
          -archivePath DogHealthApp.xcarchive \
          archive

    - name: Export IPA
      if: ${{ ((github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/devin/'))) || (github.event_name == 'pull_request' && startsWith(github.head_ref, 'devin/'))) && env.P12_BASE64 != '' }}
      run: |
        cd ios-app
        xcodebuild -exportArchive \
          -archivePath DogHealthApp.xcarchive \
          -exportPath . \
          -exportOptionsPlist ExportOptions.plist

    - name: Upload to TestFlight
      if: ${{ ((github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/devin/'))) || (github.event_name == 'pull_request' && startsWith(github.head_ref, 'devin/'))) && env.P12_BASE64 != '' }}
      run: |
        cd ios-app
        xcrun altool --upload-app \
          --type ios \
          --file DogHealthApp.ipa \
          --apiKey ${APPLE_KEY_ID} \
          --apiIssuer ${APPLE_ISSUER_ID}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-build
        path: |
          ios-app/DogHealthApp.xcarchive
          ios-app/*.ipa
        retention-days: 30
