name: iOS Build and TestFlight

on:
  push:
    branches: [ main, 'devin/*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_16.4.app/Contents/Developer
      
    - name: Show Xcode version
      run: xcodebuild -version
      
    - name: Install dependencies
      run: |
        cd ios-app
        # Install any CocoaPods dependencies if needed
        # pod install
        
    - name: Build iOS app for simulator
      run: |
        cd ios-app
        xcodebuild -project DogHealthApp.xcodeproj \
          -scheme DogHealthApp \
          -configuration Debug \
          -destination 'platform=iOS Simulator,name=iPhone 16' \
          build
          
    - name: Setup Apple certificates and provisioning profiles
      if: (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/devin/')) && secrets.APPLE_CERTIFICATE_P12
      uses: apple-actions/import-codesign-certs@v2
      with:
        p12-file-base64: ${{ secrets.APPLE_CERTIFICATE_P12 }}
        p12-password: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
        
    - name: Download provisioning profiles
      if: (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/devin/')) && secrets.APPLE_ISSUER_ID
      uses: apple-actions/download-provisioning-profiles@v1
      with:
        bundle-id: com.johnathongordon.doghealthapp
        issuer-id: ${{ secrets.APPLE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPLE_KEY_ID }}
        api-private-key: ${{ secrets.APPLE_PRIVATE_KEY }}
        
    - name: Build iOS app archive
      if: (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/devin/')) && secrets.APPLE_CERTIFICATE_P12
      run: |
        cd ios-app
        xcodebuild -project DogHealthApp.xcodeproj \
          -scheme DogHealthApp \
          -configuration Release \
          -destination 'generic/platform=iOS' \
          -archivePath DogHealthApp.xcarchive \
          archive
          
    - name: Export IPA
      if: (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/devin/')) && secrets.APPLE_CERTIFICATE_P12
      run: |
        cd ios-app
        # Update ExportOptions.plist with team ID
        sed -i '' "s/FM5C46MW5P/${{ secrets.APPLE_TEAM_ID }}/g" ExportOptions.plist
        
        xcodebuild -exportArchive \
          -archivePath DogHealthApp.xcarchive \
          -exportPath . \
          -exportOptionsPlist ExportOptions.plist
          
    - name: Upload to TestFlight
      if: (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/devin/')) && secrets.APPLE_ISSUER_ID
      uses: apple-actions/upload-testflight-build@v1
      with:
        app-path: ios-app/DogHealthApp.ipa
        issuer-id: ${{ secrets.APPLE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPLE_KEY_ID }}
        api-private-key: ${{ secrets.APPLE_PRIVATE_KEY }}
          
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-build
        path: |
          ios-app/DogHealthApp.xcarchive
          ios-app/*.ipa
        retention-days: 30
