name: iOS Build and TestFlight

on:
  push:
    branches: [ main, 'devin/*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_16.4.app/Contents/Developer
      
    - name: Show Xcode version
      run: xcodebuild -version
      
    - name: Install dependencies
      run: |
        cd ios-app
        # Install any CocoaPods dependencies if needed
        # pod install
        
    - name: Build iOS app
      run: |
        cd ios-app
        xcodebuild -project DogHealthApp.xcodeproj \
          -scheme DogHealthApp \
          -configuration Release \
          -destination 'generic/platform=iOS' \
          -archivePath DogHealthApp.xcarchive \
          archive
          
    - name: Export IPA (requires Apple Developer credentials)
      if: ${{ env.APPLE_CERTIFICATES_AVAILABLE == 'true' }}
      run: |
        cd ios-app
        xcodebuild -exportArchive \
          -archivePath DogHealthApp.xcarchive \
          -exportPath . \
          -exportOptionsPlist ExportOptions.plist
          
    - name: Upload to TestFlight (requires Apple Developer credentials)
      if: ${{ env.APPLE_CERTIFICATES_AVAILABLE == 'true' }}
      run: |
        cd ios-app
        xcrun altool --upload-app \
          --type ios \
          --file DogHealthApp.ipa \
          --username "${{ secrets.APPLE_ID }}" \
          --password "${{ secrets.APPLE_APP_PASSWORD }}"
          
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-build
        path: |
          ios-app/DogHealthApp.xcarchive
          ios-app/*.ipa
        retention-days: 30
        
    env:
      APPLE_CERTIFICATES_AVAILABLE: 'false'  # Set to 'true' when credentials are configured
